steps:
- id: 'cloudsql stop'
  name: 'gcr.io/google/cloud-sdk'  # Use the Google Cloud SDK image
  entrypoint: 'gcloud'
  args:
    - 'sql'
    - 'instances'
    - 'patch'
    - 'procurement-stage'
    - '--activation-policy=NEVER'
