steps:
- id: 'cloudsql stop'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'sql'
    - 'instances'
    - 'patch'
    - 'procurement-stage'
    - '--activation-policy=NEVER'
